# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
a=np.random.random((2,3,5))

In [5]:
a.size

30

In [6]:
np.array([2,3,5])

array([2, 3, 5])

In [17]:
np.arange([1],[2],[1])

TypeError: unsupported operand type(s) for -: 'list' and 'list'

#### 4. Print *a*.


In [7]:
print(a)

[[[0.03061912 0.67550914 0.05131391 0.30616836 0.75986932]
  [0.80037472 0.31749695 0.18452098 0.67094385 0.30940511]
  [0.61902331 0.04714719 0.76604356 0.11127396 0.83314151]]

 [[0.5616141  0.50128704 0.67510407 0.46062401 0.84378749]
  [0.96806329 0.63741385 0.91043618 0.61524415 0.94635032]
  [0.57235259 0.82411565 0.94964429 0.95766648 0.14100926]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [27]:
#this is not the good way
b=np.array([[[1,1,1],[1,1,1]],[[1,1,1],[1,1,1]],[[1,1,1],[1,1,1]],[[1,1,1],[1,1,1]],[[1,1,1],[1,1,1]]])

In [26]:
#use np.array.ones 
b=np.ones([5,3,2])

#### 6. Print *b*.


In [27]:
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [28]:
b.size


30

In [17]:
a.size

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [18]:
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,4) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [29]:
c=np.reshape(b,(2,3,5))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [30]:
d=np.add(a,c)
d

array([[[1.03061912, 1.67550914, 1.05131391, 1.30616836, 1.75986932],
        [1.80037472, 1.31749695, 1.18452098, 1.67094385, 1.30940511],
        [1.61902331, 1.04714719, 1.76604356, 1.11127396, 1.83314151]],

       [[1.5616141 , 1.50128704, 1.67510407, 1.46062401, 1.84378749],
        [1.96806329, 1.63741385, 1.91043618, 1.61524415, 1.94635032],
        [1.57235259, 1.82411565, 1.94964429, 1.95766648, 1.14100926]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [31]:
print(a)
print(d)
# D =A +1 

[[[0.03061912 0.67550914 0.05131391 0.30616836 0.75986932]
  [0.80037472 0.31749695 0.18452098 0.67094385 0.30940511]
  [0.61902331 0.04714719 0.76604356 0.11127396 0.83314151]]

 [[0.5616141  0.50128704 0.67510407 0.46062401 0.84378749]
  [0.96806329 0.63741385 0.91043618 0.61524415 0.94635032]
  [0.57235259 0.82411565 0.94964429 0.95766648 0.14100926]]]
[[[1.03061912 1.67550914 1.05131391 1.30616836 1.75986932]
  [1.80037472 1.31749695 1.18452098 1.67094385 1.30940511]
  [1.61902331 1.04714719 1.76604356 1.11127396 1.83314151]]

 [[1.5616141  1.50128704 1.67510407 1.46062401 1.84378749]
  [1.96806329 1.63741385 1.91043618 1.61524415 1.94635032]
  [1.57235259 1.82411565 1.94964429 1.95766648 1.14100926]]]


In [32]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [33]:
d-a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [34]:
d-a == c

array([[[ True, False,  True, False,  True],
        [False,  True,  True,  True, False],
        [ True,  True,  True,  True, False]],

       [[False, False,  True,  True, False],
        [ True,  True,  True,  True, False],
        [ True,  True,  True,  True, False]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [35]:
e=a*c
e

array([[[0.03061912, 0.67550914, 0.05131391, 0.30616836, 0.75986932],
        [0.80037472, 0.31749695, 0.18452098, 0.67094385, 0.30940511],
        [0.61902331, 0.04714719, 0.76604356, 0.11127396, 0.83314151]],

       [[0.5616141 , 0.50128704, 0.67510407, 0.46062401, 0.84378749],
        [0.96806329, 0.63741385, 0.91043618, 0.61524415, 0.94635032],
        [0.57235259, 0.82411565, 0.94964429, 0.95766648, 0.14100926]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
#yes . Because C is equal to 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [47]:
d

array([[[1.03061912, 1.67550914, 1.05131391, 1.30616836, 1.75986932],
        [1.80037472, 1.31749695, 1.18452098, 1.67094385, 1.30940511],
        [1.61902331, 1.04714719, 1.76604356, 1.11127396, 1.83314151]],

       [[1.5616141 , 1.50128704, 1.67510407, 1.46062401, 1.84378749],
        [1.96806329, 1.63741385, 1.91043618, 1.61524415, 1.94635032],
        [1.57235259, 1.82411565, 1.94964429, 1.95766648, 1.14100926]]])

In [54]:
np.mean(d)

1.5682521260861013

In [55]:
d_mean = np.mean(d)
print('the mean of d : ', d_mean)
d_max=d.max()
print(d_max)
d_min=d.min()
print(d_min)

the mean of d :  1.5682521260861013
1.9680632930445436
1.030619117040378


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [39]:
f=np.empty((2,3,5))

array([[[1.03061912, 1.67550914, 1.05131391, 1.30616836, 1.75986932],
        [1.80037472, 1.31749695, 1.18452098, 1.67094385, 1.30940511],
        [1.61902331, 1.04714719, 1.76604356, 1.11127396, 1.83314151]],

       [[1.5616141 , 1.50128704, 1.67510407, 1.46062401, 1.84378749],
        [1.96806329, 1.63741385, 1.91043618, 1.61524415, 1.94635032],
        [1.57235259, 1.82411565, 1.94964429, 1.95766648, 1.14100926]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [56]:
f=np.where(d==d_max,100,d)
f=np.where(d<d_max,75,f)
f=np.where(d==d_mean,50,f)
f=np.where(d<d_mean,25,f)
f=np.where(d==d_min,0,f)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [57]:
print(d)

print(f)

[[[1.03061912 1.67550914 1.05131391 1.30616836 1.75986932]
  [1.80037472 1.31749695 1.18452098 1.67094385 1.30940511]
  [1.61902331 1.04714719 1.76604356 1.11127396 1.83314151]]

 [[1.5616141  1.50128704 1.67510407 1.46062401 1.84378749]
  [1.96806329 1.63741385 1.91043618 1.61524415 1.94635032]
  [1.57235259 1.82411565 1.94964429 1.95766648 1.14100926]]]
[[[  0.  75.  25.  25.  75.]
  [ 75.  25.  25.  75.  25.]
  [ 75.  25.  75.  25.  75.]]

 [[ 25.  25.  75.  25.  75.]
  [100.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [58]:
f=np.where(d<d_max,75,f)

In [ ]:
f=np.where(d<d_max,75,f)

# Advanced Functional Programming 

In [139]:
def foo(x):
    return x%2==0

In [140]:
foo(2)

True

In [141]:
l=[10,11,13,16,17]

In [145]:
for i in l:
    print(foo(i))
    

True
False
False
True
False


In [143]:
[foo(i) for i in l]

[True, False, False, True, False]

## We dont want to iterate again, we MAP

In [147]:
map(foo,l)

In [148]:
list(map(foo,l))

[True, False, False, True, False]

In [151]:
list(map(foo,l))

[True, False, False, True, False]

In [60]:
import pandas as pd
df=pd.DataFrame([[1,2,3],[2,3,np.nan]])

In [153]:
df

0  1    2
0  1  2  3.0
1  2  3  NaN

In [154]:
#we want the range

In [156]:
for i in df:
    print(df[i].max()-df[i].min())

1
1
0.0


In [157]:
#PANDAS hate loops

In [61]:
def foo(x:pd.Series):
    return x/2
    

In [62]:
df[0].map(foo) #apply function to every element of series

0    0.5
1    1.0
Name: 0, dtype: float64

In [63]:
df[0].values

array([1, 2])

In [64]:
dct={1:'apple',2:'plum'}

In [164]:
df[0].map(dct)

0    apple
1     plum
Name: 0, dtype: object

In [165]:
df[1].map(dct) #if there's no value in the object = NaN

0    plum
1     NaN
Name: 1, dtype: object

In [166]:
# very useful to match city with countries, gender with F/M etc (like a homing missile))
# you can map a dictionnary for exemple

## filter 

In [167]:
l

[10, 11, 13, 16, 17]

In [169]:
def foo(x):
    return x%2==0
    

## The procedure that returns a list containing only those values from a given iterable that meets the criteria specified in a function 

(function should return True)

In [170]:
list(map(foo,l)) # avoid using loop

[True, False, False, True, False]

In [171]:
list(filter(foo,l)) #avoid using loop with conditional

[10, 16]

In [172]:
df.index=['mouse','cat']

In [173]:
df

0  1    2
mouse  1  2  3.0
cat    2  3  NaN

In [174]:
df.filter(like='ou', axis=0)

0  1    2
mouse  1  2  3.0

In [175]:
df.filter(like='t', axis=0)

0  1   2
cat  2  3 NaN

In [176]:
df.loc[df.index.str.contains('ouse')]

0  1    2
mouse  1  2  3.0

In [177]:
df.filter(items=[0,2], axis=1)

0    2
mouse  1  3.0
cat    2  NaN

## reduce

In [178]:
def func(a,b):
    return a+b

In [179]:
from functools import reduce

In [180]:
reduce(func, [47,11,42,13])

113

In [181]:
def func(a,b):
    return a if a>b else b

In [ ]:
47 vs 11 --> 47
47 vs 42 ---  47
47 vs 13 47

In [182]:
reduce(func, [47,11,42,13])

47

In [183]:
def func(a,b):
    return b if a>b else a

In [184]:
reduce(func, [47,11,42,13])

11

## lambda

In [185]:
#aka anonymous function

In [186]:
#cannot be saved, a kind of disposable function 

In [189]:
```python
lambda arguments: expression
```

SyntaxError: invalid syntax (<ipython-input-189-f7eb80307dcc>, line 1)

In [192]:
#regular function 
def squared(x):
    return x**2

In [196]:
list(map(squared, l))

[100, 121, 169, 256, 289]

In [197]:
square=lambda x:x **2

In [199]:
list(map(square,l))

[100, 121, 169, 256, 289]

In [200]:
list(map(lambda x: x**2,l))

[100, 121, 169, 256, 289]

In [201]:
squared(11)

121

In [202]:
square(11)

121

In [203]:
(lambda x: x**2)(11)

121

In [204]:
define a normal and lambda function that would return me a result of division with 0 in case of division by 0


SyntaxError: invalid syntax (<ipython-input-204-c6f46b02b27d>, line 1)

In [208]:
def div(x,y):
       return x/y if y!=0 else y

In [209]:
div(4,2)

2.0

In [210]:
div(4,0)

0

In [211]:
div2=lambda x,y: x/y if y!=0 else y

In [212]:
div2(4,2)

2.0

In [213]:
div2(4,0)

0

In [214]:
def generate_range(lower):
    return lambda upper: range(lower,upper)    #this is a function which returns a function

In [215]:
func1=generate_range(1)

In [216]:
func1(10)

range(1, 10)

In [217]:
func1(5)

range(1, 5)

In [218]:
func5=generate_range(5)

In [219]:
func5(10)

range(5, 10)

In [220]:
func5(22)

range(5, 22)

In [ ]:
list(map(lambda x: x.replace('-',' ').title(), list_of_topics))

In [221]:
[x.replace('-',' ').title() for x in list_of_topics]

NameError: name 'list_of_topics' is not defined

In [222]:
dct_of_topics={x:len(x) for x in list_of_topics}

NameError: name 'list_of_topics' is not defined

In [223]:
from operator import itemgetter

dict(sorted(dct_of_topics.items(),

In [ ]:
#beter way to do it
dict(sorted(dct_of_topics.items(), key=lambda x: x[1], reverse=True))

In [ ]:
dct_of_topics.items()    
#items give tuples

# Map , Apply, Applymap + Lambda in Pandas

In [ ]:
*Map - maps a function / dict to every value in the Series
*Apply - applies a function to every value in the series or every serie in the dataframe (both rows and columns)
*applymap - applies a fucntion to every value in the dataframe

In [224]:
df=pd.read_csv('https://ironhack.school/asset-v1:IRONHACK+DAFT+201910_PAR+type@asset+block@IMDB-Movie-Data.csv')

In [225]:
df.head()

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0  
3     7.2   60545              270.32       59.0  
4     6.2  393727              325.02       40.0

In [227]:
df.Rating.max()

9.0

In [229]:
df.Rating.idxmax()

54

In [230]:
df.loc[df.Rating.idxmax()]

Rank                                                                 55
Title                                                   The Dark Knight
Genre                                                Action,Crime,Drama
Description           When the menace known as the Joker wreaks havo...
Director                                              Christopher Nolan
Actors                Christian Bale, Heath Ledger, Aaron Eckhart,Mi...
Year                                                               2008
Runtime (Minutes)                                                   152
Rating                                                                9
Votes                                                           1791916
Revenue (Millions)                                               533.32
Metascore                                                            82
Name: 54, dtype: object

Rescale Rating column to be up to 5

In [231]:
df.Rating/2    # option 1

0      4.05
1      3.50
2      3.65
3      3.60
4      3.10
       ... 
995    3.10
996    2.75
997    3.10
998    2.80
999    2.65
Name: Rating, Length: 1000, dtype: float64

In [232]:
df.Rating.map(lambda x: x/2) # option 2 using MAP

0      4.05
1      3.50
2      3.65
3      3.60
4      3.10
       ... 
995    3.10
996    2.75
997    3.10
998    2.80
999    2.65
Name: Rating, Length: 1000, dtype: float64

calculate the range 

In [233]:
def range_column(x: pd.Series):
    return x.max()-x.min()

In [235]:
#create a dataframe
df[['Rating', 'Metascore']].apply(range_column)

Rating        7.1
Metascore    89.0
dtype: float64

In [236]:
def missing_col(x:pd.Series):
    return x.isna().sum()

In [237]:
df.apply(missing_col)

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [238]:
df._get_numeric_data().apply(sum, axis=1)

0      759627.23
1      488156.46
2      159949.42
3       63009.52
4      396242.22
         ...    
995          NaN
996     76319.04
997     73917.21
998          NaN
999     15573.94
Length: 1000, dtype: float64


CHALLENGE 

select an action movie for me to watch tonight

I don't like fantasy movies, so action fantasy doesnt count
I can accept action, action/thrillers or Action/Adventure movies 

In [242]:
df.tail()

Rank                   Title                  Genre  \
995   996    Secret in Their Eyes    Crime,Drama,Mystery   
996   997         Hostel: Part II                 Horror   
997   998  Step Up 2: The Streets    Drama,Music,Romance   
998   999            Search Party       Adventure,Comedy   
999  1000              Nine Lives  Comedy,Family,Fantasy   

                                           Description          Director  \
995  A tight-knit team of rising investigators, alo...         Billy Ray   
996  Three American college students studying abroa...          Eli Roth   
997  Romantic sparks occur between two dance studen...        Jon M. Chu   
998  A pair of friends embark on a mission to reuni...    Scot Armstrong   
999  A stuffy businessman finds himself trapped ins...  Barry Sonnenfeld   

                                                Actors  Year  \
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015   
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007   
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008   
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014   
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016   

     Runtime (Minutes)  Rating  Votes  Revenue (Millions)  Metascore  
995                111     6.2  27585                 NaN       45.0  
996                 94     5.5  73152               17.54       46.0  
997                 98     6.2  70699               58.01       50.0  
998                 93     5.6   4881                 NaN       22.0  
999                 87     5.3  12435               19.64       11.0

In [261]:
df.loc[df.Genre.str.contains('Action', case=False)]    #case false makes lower upper case ok 

In [263]:
df.loc[df.Genre.str.contains('Adventure', case=False) & df.Genre.str.contains('Action', case=False)]

In [270]:
#just action
df.Genre=='Action';
#have only 2 genres
df.Genre.str.count(',')+1==2
#have action among genres
df.Genre.str.contains('Action', case=False)
#are combined from action thriller adventure only
(df.Genre.str.split(',').map(set)-set(['Action','Thriller','Adventure']))==set()

0      False
1      False
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998    False
999    False
Name: Genre, Length: 1000, dtype: bool

In [ ]:
#1 or (#2 and #3 and #4)
#either it is just an action or it is an action + thriller or adventure

In [275]:
df[df.Genre.str.split(',').map(set).apply(lambda x: 
                                    (len(x)<3)&
                                    ('Action' in x) &
                                    (x-{'Action','Thriller','Adventure'})==set())]

TypeError: unsupported operand type(s) for &: 'bool' and 'set'

In [274]:
df[df.Genre.str.split(',').map(set).apply(lambda x: 
                                          (len(x)<3) &
                                          ("Action" in x) &
                                          ((x-{'Action','Thriller',"Adventure"})==set())
                                      )]

Rank                   Title             Genre  \
17     18            Jason Bourne   Action,Thriller   
123   124    Boyka: Undisputed IV            Action   
124   125   The Dark Knight Rises   Action,Thriller   
284   285                Hercules  Action,Adventure   
344   345            Spider-Man 3  Action,Adventure   
368   369  The Amazing Spider-Man  Action,Adventure   
410   411                   Taken   Action,Thriller   
453   454      Olympus Has Fallen   Action,Thriller   
580   581    Kickboxer: Vengeance            Action   
624   625                 Taken 3   Action,Thriller   
777   778              Final Girl   Action,Thriller   
844   845             Unstoppable   Action,Thriller   
872   873                Red Dawn   Action,Thriller   
923   924               No Escape   Action,Thriller   

                                           Description           Director  \
17   The CIA's most dangerous former operative is d...    Paul Greengrass   
123  In the fourth installment of the fighting fran...    Todor Chapkanov   
124  Eight years after the Joker's reign of anarchy...  Christopher Nolan   
284  Having endured his legendary twelve labors, He...       Brett Ratner   
344  A strange black entity from another world bond...          Sam Raimi   
368  After Peter Parker is bitten by a genetically ...          Marc Webb   
410  A retired CIA agent travels across Europe and ...       Pierre Morel   
453  Disgraced Secret Service agent (and former pre...      Antoine Fuqua   
580         A kick boxer is out to avenge his brother.     John Stockwell   
624  Ex-government operative Bryan Mills is accused...    Olivier Megaton   
777  A man teaches a young woman how to become a co...      Tyler Shields   
844  With an unmanned, half-mile-long freight train...         Tony Scott   
872  A group of teenagers look to save their town f...        Dan Bradley   
923  In their new overseas home, an American family...  John Erick Dowdle   

                                                Actors  Year  \
17   Matt Damon, Tommy Lee Jones, Alicia Vikander,V...  2016   
123  Scott Adkins, Teodora Duhovnikova, Alon Aboutb...  2016   
124  Christian Bale, Tom Hardy, Anne Hathaway,Gary ...  2012   
284  Dwayne Johnson, John Hurt, Ian McShane, Joseph...  2014   
344  Tobey Maguire, Kirsten Dunst, Topher Grace, Th...  2007   
368  Andrew Garfield, Emma Stone, Rhys Ifans, Irrfa...  2012   
410  Liam Neeson, Maggie Grace, Famke Janssen, Lela...  2008   
453  Gerard Butler, Aaron Eckhart, Morgan Freeman,A...  2013   
580  Dave Bautista, Alain Moussi, Gina Carano, Jean...  2016   
624  Liam Neeson, Forest Whitaker, Maggie Grace,Fam...  2014   
777  Abigail Breslin, Wes Bentley, Logan Huffman,Al...  2015   
844  Denzel Washington, Chris Pine, Rosario Dawson,...  2010   
872  Chris Hemsworth, Isabel Lucas, Josh Hutcherson...  2012   
923  Lake Bell, Pierce Brosnan, Owen Wilson,Chatcha...  2015   

     Runtime (Minutes)  Rating    Votes  Revenue (Millions)  Metascore  
17                 123     6.7   150823              162.16       58.0  
123                 86     7.4    10428                 NaN        NaN  
124                164     8.5  1222645              448.13       78.0  
284                 98     6.0   122838               72.66       47.0  
344                139     6.2   406219              336.53       59.0  
368                136     7.0   474320              262.03       66.0  
410                 93     7.8   502961              145.00       50.0  
453                119     6.5   214994               98.90       41.0  
580                 90     4.9     6809              131.56       37.0  
624                109     6.0   144715               89.25       26.0  
777                 90     4.7     9026                 NaN       56.0  
844                 98     6.8   157499               81.56       69.0  
872                 93     5.4    64584               44.80       31.0  
923                103     6.8    57921 

Calculate the average number of words in the description and actors

In [278]:
df.Description.str.split().map(len).mean()
df.Actors.str.split().map(len).mean()

7.86

In [279]:
df[['Description','Actors']].applymap(lambda x: len(x.split())).mean()

Description    27.921
Actors          7.860
dtype: float64

In [ ]:
#apply (90% of time) to series and dataframe
#10% of time use map to map a dictionnary