# Numpy

In [66]:
import numpy as np


In [79]:
a=np.random.random((2,2))
b=np.random.random((3,2,2))
c=np.random.random((2,2,2,2))
c=np.

In [72]:
a

array([[0.13455788, 0.91354294],
       [0.51048477, 0.41017805]])

In [69]:
b

array([[[0.95006417, 0.150096  ],
        [0.4512144 , 0.79672594]],

       [[0.16046202, 0.88226662],
        [0.16007468, 0.5164372 ]],

       [[0.18928664, 0.01531686],
        [0.28273179, 0.37468172]]])

In [76]:
c

array([[[[0.04711716, 0.66336807],
         [0.87513124, 0.45596168]],

        [[0.80680423, 0.99956963],
         [0.78919478, 0.26144125]]],


       [[[0.91975195, 0.1469119 ],
         [0.67739108, 0.29559167]],

        [[0.23290305, 0.18494313],
         [0.89677985, 0.28773663]]]])

In [81]:
a

array([[0.92054923, 0.21567567],
       [0.66066279, 0.97341485]])

In [74]:
a[0]

array([0.13455788, 0.91354294])

In [82]:
a[1]

array([0.66066279, 0.97341485])

In [83]:
a[:,1]

array([0.21567567, 0.97341485])

In [84]:
b

array([[[0.81229761, 0.90578697],
        [0.4289865 , 0.89112125]],

       [[0.61255706, 0.49226178],
        [0.89776816, 0.70005665]],

       [[0.33198378, 0.63771858],
        [0.02901839, 0.95120034]]])

In [85]:
b[0]  # this selects the first ELEMENT (not rows or columns bzcause only one number inside the brackets)

array([[0.81229761, 0.90578697],
       [0.4289865 , 0.89112125]])

In [86]:
b[:,0]

array([[0.81229761, 0.90578697],
       [0.61255706, 0.49226178],
       [0.33198378, 0.63771858]])

In [87]:
b[:,:,1] # from all matrices from all rows from all colums, 2n element

array([[0.90578697, 0.89112125],
       [0.49226178, 0.70005665],
       [0.63771858, 0.95120034]])

In [88]:
c

array([[[[0.74433449, 0.49168291],
         [0.313271  , 0.30039541]],

        [[0.76431792, 0.6503141 ],
         [0.24976849, 0.93483041]]],


       [[[0.86642455, 0.28792787],
         [0.75712497, 0.86562892]],

        [[0.74790331, 0.44671504],
         [0.47654831, 0.79922615]]]])

In [89]:
c[0,1,1]

array([0.24976849, 0.93483041])

In [90]:
c[:,:,:,1]

array([[[0.49168291, 0.30039541],
        [0.6503141 , 0.93483041]],

       [[0.28792787, 0.86562892],
        [0.44671504, 0.79922615]]])

In [91]:
a.T

array([[0.92054923, 0.66066279],
       [0.21567567, 0.97341485]])

In [92]:
a.transpose()

array([[0.92054923, 0.66066279],
       [0.21567567, 0.97341485]])

In [93]:
c

array([[[[0.74433449, 0.49168291],
         [0.313271  , 0.30039541]],

        [[0.76431792, 0.6503141 ],
         [0.24976849, 0.93483041]]],


       [[[0.86642455, 0.28792787],
         [0.75712497, 0.86562892]],

        [[0.74790331, 0.44671504],
         [0.47654831, 0.79922615]]]])

In [94]:
c.sort(axis=0)

In [95]:
c

array([[[[0.74433449, 0.28792787],
         [0.313271  , 0.30039541]],

        [[0.74790331, 0.44671504],
         [0.24976849, 0.79922615]]],


       [[[0.86642455, 0.49168291],
         [0.75712497, 0.86562892]],

        [[0.76431792, 0.6503141 ],
         [0.47654831, 0.93483041]]]])

In [96]:
c.sort(axis=1)

In [97]:
c

array([[[[0.74433449, 0.28792787],
         [0.24976849, 0.30039541]],

        [[0.74790331, 0.44671504],
         [0.313271  , 0.79922615]]],


       [[[0.76431792, 0.49168291],
         [0.47654831, 0.86562892]],

        [[0.86642455, 0.6503141 ],
         [0.75712497, 0.93483041]]]])