In [1]:
import numpy as np

In [15]:
a=np.random.random((2,2))
b=np.random.random((3,2,2))
c=np.arange(16).reshape((2,2,2,2))

In [16]:
a

array([[0.54505349, 0.2469789 ],
       [0.2493157 , 0.46031084]])

In [17]:
b

array([[[0.05289432, 0.97800037],
        [0.39094252, 0.38308627]],

       [[0.36015093, 0.32695925],
        [0.72772366, 0.3774145 ]],

       [[0.52720279, 0.67330391],
        [0.25763909, 0.12749418]]])

In [19]:
c

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [21]:
a

array([[0.54505349, 0.2469789 ],
       [0.2493157 , 0.46031084]])

In [22]:
a[0]

array([0.54505349, 0.2469789 ])

In [23]:
a[1]

array([0.2493157 , 0.46031084])

In [24]:
a[:,0]

array([0.54505349, 0.2493157 ])

In [25]:
a[:,1]

array([0.2469789 , 0.46031084])

In [26]:
b

array([[[0.05289432, 0.97800037],
        [0.39094252, 0.38308627]],

       [[0.36015093, 0.32695925],
        [0.72772366, 0.3774145 ]],

       [[0.52720279, 0.67330391],
        [0.25763909, 0.12749418]]])

In [27]:
b[0]

array([[0.05289432, 0.97800037],
       [0.39094252, 0.38308627]])

In [28]:
b[:,0]

array([[0.05289432, 0.97800037],
       [0.36015093, 0.32695925],
       [0.52720279, 0.67330391]])

In [29]:
b[:,:,1]

array([[0.97800037, 0.38308627],
       [0.32695925, 0.3774145 ],
       [0.67330391, 0.12749418]])

In [34]:
c

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [33]:
c[0,1,1]

array([6, 7])

In [35]:
c[:,:,:,1]

array([[[ 1,  3],
        [ 5,  7]],

       [[ 9, 11],
        [13, 15]]])

In [37]:
b

array([[[0.05289432, 0.97800037],
        [0.39094252, 0.38308627]],

       [[0.36015093, 0.32695925],
        [0.72772366, 0.3774145 ]],

       [[0.52720279, 0.67330391],
        [0.25763909, 0.12749418]]])

In [38]:
b[0]

array([[0.05289432, 0.97800037],
       [0.39094252, 0.38308627]])

In [39]:
a.T

array([[0.54505349, 0.2493157 ],
       [0.2469789 , 0.46031084]])

In [40]:
a.transpose()

array([[0.54505349, 0.2493157 ],
       [0.2469789 , 0.46031084]])

In [42]:
c.sum()

120

In [45]:
c

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [44]:
c.sum(axis=0)

array([[[ 8, 10],
        [12, 14]],

       [[16, 18],
        [20, 22]]])

In [46]:
c.sum(axis=3)

array([[[ 1,  5],
        [ 9, 13]],

       [[17, 21],
        [25, 29]]])

In [47]:
c.sort()

In [48]:
c

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [50]:
c=np.arange(16,0,-1).reshape((2,2,2,2))

In [51]:
c

array([[[[16, 15],
         [14, 13]],

        [[12, 11],
         [10,  9]]],


       [[[ 8,  7],
         [ 6,  5]],

        [[ 4,  3],
         [ 2,  1]]]])

In [52]:
c.sort()

In [54]:
c.sort(axis=0)

In [57]:
c.sort(axis=1)
c.sort(axis=2)
c

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [58]:
b

array([[[0.05289432, 0.97800037],
        [0.39094252, 0.38308627]],

       [[0.36015093, 0.32695925],
        [0.72772366, 0.3774145 ]],

       [[0.52720279, 0.67330391],
        [0.25763909, 0.12749418]]])

In [59]:
b.sort(axis=0)

In [60]:
b

array([[[0.05289432, 0.32695925],
        [0.25763909, 0.12749418]],

       [[0.36015093, 0.67330391],
        [0.39094252, 0.3774145 ]],

       [[0.52720279, 0.97800037],
        [0.72772366, 0.38308627]]])

# Lab Review

In [5]:
import numpy as np

In [6]:
print(np.__version__)

1.19.2


In [7]:
a=np.random.random((2,3,5))

In [8]:
a

array([[[0.16934179, 0.47340438, 0.5381245 , 0.26551718, 0.21137736],
        [0.25483375, 0.94155855, 0.9065304 , 0.1185789 , 0.36863527],
        [0.63283801, 0.98571907, 0.85260574, 0.10684635, 0.50388784]],

       [[0.33050999, 0.21297503, 0.6394684 , 0.14759132, 0.85992124],
        [0.38588075, 0.10730984, 0.30261959, 0.96705553, 0.67404607],
        [0.14952381, 0.01864145, 0.07535842, 0.38588098, 0.15580808]]])

In [9]:
b=np.ones((5,2,3))

In [10]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
a.size, b.size

(30, 30)

In [12]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [13]:
c=b.transpose((1,2,0))

In [14]:
d=a+c

In [15]:
a

array([[[0.16934179, 0.47340438, 0.5381245 , 0.26551718, 0.21137736],
        [0.25483375, 0.94155855, 0.9065304 , 0.1185789 , 0.36863527],
        [0.63283801, 0.98571907, 0.85260574, 0.10684635, 0.50388784]],

       [[0.33050999, 0.21297503, 0.6394684 , 0.14759132, 0.85992124],
        [0.38588075, 0.10730984, 0.30261959, 0.96705553, 0.67404607],
        [0.14952381, 0.01864145, 0.07535842, 0.38588098, 0.15580808]]])

In [16]:
d

array([[[1.16934179, 1.47340438, 1.5381245 , 1.26551718, 1.21137736],
        [1.25483375, 1.94155855, 1.9065304 , 1.1185789 , 1.36863527],
        [1.63283801, 1.98571907, 1.85260574, 1.10684635, 1.50388784]],

       [[1.33050999, 1.21297503, 1.6394684 , 1.14759132, 1.85992124],
        [1.38588075, 1.10730984, 1.30261959, 1.96705553, 1.67404607],
        [1.14952381, 1.01864145, 1.07535842, 1.38588098, 1.15580808]]])

In [17]:
e=a*c

In [18]:
a

array([[[0.16934179, 0.47340438, 0.5381245 , 0.26551718, 0.21137736],
        [0.25483375, 0.94155855, 0.9065304 , 0.1185789 , 0.36863527],
        [0.63283801, 0.98571907, 0.85260574, 0.10684635, 0.50388784]],

       [[0.33050999, 0.21297503, 0.6394684 , 0.14759132, 0.85992124],
        [0.38588075, 0.10730984, 0.30261959, 0.96705553, 0.67404607],
        [0.14952381, 0.01864145, 0.07535842, 0.38588098, 0.15580808]]])

In [19]:
e

array([[[0.16934179, 0.47340438, 0.5381245 , 0.26551718, 0.21137736],
        [0.25483375, 0.94155855, 0.9065304 , 0.1185789 , 0.36863527],
        [0.63283801, 0.98571907, 0.85260574, 0.10684635, 0.50388784]],

       [[0.33050999, 0.21297503, 0.6394684 , 0.14759132, 0.85992124],
        [0.38588075, 0.10730984, 0.30261959, 0.96705553, 0.67404607],
        [0.14952381, 0.01864145, 0.07535842, 0.38588098, 0.15580808]]])

In [20]:
d_max=d.max()

In [21]:
d_min=d.min()

In [22]:
d_mean=d.mean()

In [23]:
f=np.zeros((2,3,5))

In [24]:
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [30]:
for idx1, m_1 in enumerate(d):
    for idx2, m_2 in enumerate(m_1):
        for idx, i in enumerate(m_2):
            if d_min < i < d_mean:
                f[idx1, idx2, idx] = 25
            elif d_mean < i < d_max:
                f[idx1, idx2, idx] = 75
            elif i == d_mean:
                f[idx1, idx2, idx] = 50
            elif i == d_min:
                f[idx1, idx2, idx] = 0
            elif i == d_max:
                f[idx1, idx2, idx] = 100

In [31]:
d_max

1.9857190660926003

In [32]:
d

array([[[1.16934179, 1.47340438, 1.5381245 , 1.26551718, 1.21137736],
        [1.25483375, 1.94155855, 1.9065304 , 1.1185789 , 1.36863527],
        [1.63283801, 1.98571907, 1.85260574, 1.10684635, 1.50388784]],

       [[1.33050999, 1.21297503, 1.6394684 , 1.14759132, 1.85992124],
        [1.38588075, 1.10730984, 1.30261959, 1.96705553, 1.67404607],
        [1.14952381, 1.01864145, 1.07535842, 1.38588098, 1.15580808]]])

In [33]:
f

array([[[ 25.,  75.,  75.,  25.,  25.],
        [ 25.,  75.,  75.,  25.,  25.],
        [ 75., 100.,  75.,  25.,  75.]],

       [[ 25.,  25.,  75.,  25.,  75.],
        [ 25.,  25.,  25.,  75.,  75.],
        [ 25.,   0.,  25.,  25.,  25.]]])

In [102]:
f=np.where(d==d_max,100,d)
f=np.where(d<d_max, 75, f)
f=np.where(d==d_mean, 50, f)
f=np.where(d<d_mean, 25, f)
f=np.where(d==d_min, 0, f)

In [103]:
f

array([[[ 75.,  75.,  25.,  75.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  75.,  25., 100.,  25.]],

       [[ 75.,  25.,   0.,  25.,  25.],
        [ 75.,  75.,  75.,  25.,  25.],
        [ 25.,  25.,  25.,  25.,  75.]]])

In [104]:
g=np.where(f==100,'E',f)
g=np.where(f==75, 'D', g)
g=np.where(f==50, 'C', g)
g=np.where(f==25, 'B', g)
g=np.where(f==0, 'A', g)

In [105]:
g

array([[['D', 'D', 'B', 'D', 'D'],
        ['D', 'D', 'B', 'B', 'B'],
        ['D', 'D', 'B', 'E', 'B']],

       [['D', 'B', 'A', 'B', 'B'],
        ['D', 'D', 'D', 'B', 'B'],
        ['B', 'B', 'B', 'B', 'D']]], dtype='<U32')

# Advanced Functional Programming

## map

In [114]:
def foo(x):
    return x%2==0

In [109]:
foo(2)

True

In [110]:
l=[10,11,13,16,17]

In [116]:
[foo(i) for i in l]

[True, False, False, True, False]

In [117]:
map(foo, l)

In [118]:
list(map(foo,l))

[True, False, False, True, False]

In [125]:
import pandas as pd
df=pd.DataFrame([[1,2,3],[2,3,np.nan]])


In [126]:
df

0  1    2
0  1  2  3.0
1  2  3  NaN

In [128]:
for i in df:
    print(df[i].max()-df[i].min())

1
1
0.0


In [134]:
def foo(x):
    return x/2

In [136]:
df[0].map(foo)

0    0.5
1    1.0
Name: 0, dtype: float64

In [138]:
df[0].values

array([1, 2], dtype=int64)

In [139]:
dct={1:'apple',2:'plum'}

In [142]:
df[0]

0    1
1    2
Name: 0, dtype: int64

In [141]:
df[0].map(dct)

0    apple
1     plum
Name: 0, dtype: object

In [144]:
df[1].map(dct)

0    plum
1     NaN
Name: 1, dtype: object

In [145]:
df[0]/2

0    0.5
1    1.0
Name: 0, dtype: float64

## filter

In [146]:
l

[10, 11, 13, 16, 17]

In [149]:
def foo(x):
    return x%2==0

The procedure that returns a list containing only those values from a given iterable that meets the criteria specified in the function (function should return True)

In [150]:
list(map(foo, l))

[True, False, False, True, False]

In [151]:
list(filter(foo,l))

[10, 16]

In [152]:
df.index=['mouse','cat']

In [153]:
df

0  1    2
mouse  1  2  3.0
cat    2  3  NaN

In [154]:
df.filter(like='ouse',axis=0)

0  1    2
mouse  1  2  3.0

In [155]:
df.filter(like='ou',axis=0)

0  1    2
mouse  1  2  3.0

In [156]:
df.filter(like='t',axis=0)

0  1   2
cat  2  3 NaN

In [159]:
df.loc[df.index.str.contains('ouse')]

0  1    2
mouse  1  2  3.0

In [160]:
df.filter(items=[0,2],axis=1)

0    2
mouse  1  3.0
cat    2  NaN

## reduce

<img src='https://www.python-course.eu/images/reduce_diagram.png'>

In [161]:
def func(a,b):
    return a+b

In [162]:
from functools import reduce

In [163]:
reduce(func, [47,11,42,13])

113

In [164]:
def func(a,b):
    return a if a>b else b

47 vs 11 --> 47  
47 vs 42 --> 47  
47 vs 13 --> 47  

In [165]:
reduce(func, [47,11,42,13])

47

In [166]:
def func(a,b):
    return b if a>b else a

In [167]:
reduce(func, [47,11,42,13])

11

## lambda

```python
lambda arguments: expression
```

In [172]:
# regular function
def squared(x):
    return x**2

In [173]:
list(map(squared, l))

[100, 121, 169, 256, 289]

In [174]:
square=lambda x: x**2

In [175]:
list(map(square, l))

[100, 121, 169, 256, 289]

In [176]:
list(map(lambda x: x**2, l))

[100, 121, 169, 256, 289]

In [177]:
squared(11)

121

In [178]:
square(11)

121

In [179]:
(lambda x: x**2)(11)

121

define a normal and lambda function that would return me a result of division with 0 in case of division by 0

In [180]:
def div(x,y):
    return x/y if y!=0 else y

In [181]:
div(4,2)

2.0

In [182]:
div(4,0)

0

In [183]:
div2=lambda x,y: x/y if y!=0 else y

In [184]:
div2(4,2)

2.0

In [185]:
div2(4,0)

0

In [186]:
def generate_range(lower):
    return lambda upper: range(lower,upper)

In [187]:
func1=generate_range(1)

In [189]:
func1(10)

range(1, 10)

In [190]:
func1(5)

range(1, 5)

In [191]:
func5=generate_range(5)
func5(10)

range(5, 10)

In [192]:
func5(22)

range(5, 22)

In [193]:
func5=generate_range(-10000000)
func5(10)

range(-10000000, 10)

In [194]:
list_of_topics=['python-programming','mysql','web-scrapping','tableau','data-viz','statistics','machine-learning','neural-nets']


In [195]:
list_of_topics

['python-programming',
 'mysql',
 'web-scrapping',
 'tableau',
 'data-viz',
 'statistics',
 'machine-learning',
 'neural-nets']

In [199]:
list_of_topics=list(map(lambda x: x.replace('-',' ').title(), list_of_topics))

In [197]:
[x.replace('-',' ').title() for x in list_of_topics]

['Python Programming',
 'Mysql',
 'Web Scrapping',
 'Tableau',
 'Data Viz',
 'Statistics',
 'Machine Learning',
 'Neural Nets']

In [201]:
dct_of_topics={x:len(x) for x in list_of_topics}

In [202]:
from operator import itemgetter

In [204]:
dict(sorted(dct_of_topics.items(), key=itemgetter(1), reverse=True))

{'Python Programming': 18,
 'Machine Learning': 16,
 'Web Scrapping': 13,
 'Neural Nets': 11,
 'Statistics': 10,
 'Data Viz': 8,
 'Tableau': 7,
 'Mysql': 5}

In [205]:
dict(sorted(dct_of_topics.items(), 
            key= lambda x: x[1], 
            reverse=True))

{'Python Programming': 18,
 'Machine Learning': 16,
 'Web Scrapping': 13,
 'Neural Nets': 11,
 'Statistics': 10,
 'Data Viz': 8,
 'Tableau': 7,
 'Mysql': 5}

In [206]:
dct_of_topics.items()

dict_items([('Python Programming', 18), ('Mysql', 5), ('Web Scrapping', 13), ('Tableau', 7), ('Data Viz', 8), ('Statistics', 10), ('Machine Learning', 16), ('Neural Nets', 11)])

# Map, Apply, Applymap + Lambda in Pandas

* Map - maps a function/dict to every value in the Series
* Apply - applies a function to every value in the Series or every Serie in the DataFrame (both rows and columns)
* Applymap - applies a function to every value in the DataFrame

In [207]:
df=pd.read_csv('https://ironhack.school/asset-v1:IRONHACK+DAFT+201910_PAR+type@asset+block@IMDB-Movie-Data.csv')

In [208]:
df.head()

Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1     2               Prometheus  Adventure,Mystery,Sci-Fi   
2     3                    Split           Horror,Thriller   
3     4                     Sing   Animation,Comedy,Family   
4     5            Suicide Squad  Action,Adventure,Fantasy   

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn   
1  Following clues to the origin of mankind, a te...          Ridley Scott   
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan   
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet   
4  A secret government agency recruits some of th...            David Ayer   

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121   
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124   
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117   
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108   
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123   

   Rating   Votes  Revenue (Millions)  Metascore  
0     8.1  757074              333.13       76.0  
1     7.0  485820              126.46       65.0  
2     7.3  157606              138.12       62.0  
3     7.2   60545              270.32       59.0  
4     6.2  393727              325.02       40.0

In [210]:
df.Rating.max()

9.0

In [211]:
df.Rating.idxmax()

54

In [212]:
df.loc[df.Rating.idxmax()]

Rank                                                                 55
Title                                                   The Dark Knight
Genre                                                Action,Crime,Drama
Description           When the menace known as the Joker wreaks havo...
Director                                              Christopher Nolan
Actors                Christian Bale, Heath Ledger, Aaron Eckhart,Mi...
Year                                                               2008
Runtime (Minutes)                                                   152
Rating                                                                9
Votes                                                           1791916
Revenue (Millions)                                               533.32
Metascore                                                            82
Name: 54, dtype: object

Rescale Rating column to be up to 5

In [215]:
df.Rating.map(lambda x: x/2);

In [216]:
def range_column(x: pd.Series):
    return x.max()-x.min()

In [219]:
df[['Rating','Metascore']].apply(range_column)

Rating        7.1
Metascore    89.0
dtype: float64

In [220]:
def missing_col(x:pd.Series):
    return x.isna().sum()

In [221]:
df.apply(missing_col)

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [224]:
df._get_numeric_data().apply(sum, axis=1)

0      759627.23
1      488156.46
2      159949.42
3       63009.52
4      396242.22
         ...    
995          NaN
996     76319.04
997     73917.21
998          NaN
999     15573.94
Length: 1000, dtype: float64

Select an action movie for me to watch tonight. 

I don't like fantasy movies, so action fantasy doesnt count.  
I can accept Action, Action/Thrillers or Action/Adventure movies.

In [229]:
df[df.Genre.str.contains('action',case=False)];

In [231]:
df[df.Genre.str.contains('action',case=False) &df.Genre.str.contains('thriller',case=False)]

Rank                                  Title                      Genre  \
17     18                           Jason Bourne            Action,Thriller   
53     54                              John Wick      Action,Crime,Thriller   
69     70                      Deepwater Horizon      Action,Drama,Thriller   
84     85                          Furious Seven      Action,Crime,Thriller   
110   111                   The Belko Experiment     Action,Horror,Thriller   
124   125                  The Dark Knight Rises            Action,Thriller   
134   135                              Furious 6      Action,Crime,Thriller   
164   165                          Casino Royale  Action,Adventure,Thriller   
169   170                                Spectre  Action,Adventure,Thriller   
233   234     Mission: Impossible - Rogue Nation  Action,Adventure,Thriller   
270   271                                Skyfall  Action,Adventure,Thriller   
300   301                          The Equalizer      Action,Crime,Thriller   
308   309  The Fast and the Furious: Tokyo Drift      Action,Crime,Thriller   
319   320                              Fast Five      Action,Crime,Thriller   
322   323                             RocknRolla      Action,Crime,Thriller   
323   324                                In Time     Action,Sci-Fi,Thriller   
340   341                         Fast & Furious      Action,Crime,Thriller   
342   343                       White House Down      Action,Drama,Thriller   
375   376                                Collide      Action,Crime,Thriller   
379   380                      The Expendables 3  Action,Adventure,Thriller   
410   411                                  Taken            Action,Thriller   
420   421                                  Hanna      Action,Drama,Thriller   
426   427           Sin City: A Dame to Kill For      Action,Crime,Thriller   
427   428                   The Bourne Ultimatum    Action,Mystery,Thriller   
433   434   Mission: Impossible - Ghost Protocol  Action,Adventure,Thriller   
453   454                     Olympus Has Fallen            Action,Thriller   
468   469                             District 9     Action,Sci-Fi,Thriller   
500   501         Maze Runner: The Scorch Trials     Action,Sci-Fi,Thriller   
532   533                                Deja Vu     Action,Sci-Fi,Thriller   
533   534                                   Lucy     Action,Sci-Fi,Thriller   
560   561                        The Expendables  Action,Adventure,Thriller   
585   586                            Ghost Rider    Action,Fantasy,Thriller   
624   625                                Taken 3            Action,Thriller   
679   680                     The Age of Shadows      Action,Drama,Thriller   
698   699                  Live Free or Die Hard  Action,Adventure,Thriller   
763   764                              Eagle Eye    Action,Mystery,Thriller   
770   771                      Quantum of Solace  Action,Adventure,Thriller   
771   772                         The Assignment      Action,Crime,Thriller   
777   778                             Final Girl            Action,Thriller   
780   781                                Unknown    Action,Mystery,Thriller   
794   795                         Man on a Ledge      Action,Crime,Thriller   
803   804              Jack Ryan: Shadow Recruit      Action,Drama,Thriller   
828   829                             Grindhouse     Action,Horror,Thriller   
844   845                            Unstoppable            Action,Thriller   
869   870                Mission: Impossible III  Action,Adventure,Thriller   
872   873                               Red Dawn            Action,Thriller   
894   895                                  Rambo        Action,Thriller,War   
916   917                      The Expendables 2  Action,Adventure,Thriller   
923   924                              No Escape            Action,Thriller   
938   939                The Siege of Jadotville      A

In [241]:
#have at most 2 genres
(df.Genre.str.count(',')+1)<3;
#have action among genres
df.Genre.str.contains('action',case=False);
#are combined from action, thriller, adventure only
(df.Genre.str.split(',').map(set)-set(['Action','Thriller',"Adventure"]))==set()

0      False
1      False
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998    False
999    False
Name: Genre, Length: 1000, dtype: bool

In [248]:
#2 and #3 and #4
#either it is just an action or it is an action +thriller or adventure

In [257]:
df[df.Genre.str.split(',').map(set).apply(lambda x: 
                                          (len(x)<3) &
                                          ("Action" in x) &
                                          ((x-{'Action','Thriller',"Adventure"})==set())
                                      )]

Rank                   Title             Genre  \
17     18            Jason Bourne   Action,Thriller   
123   124    Boyka: Undisputed IV            Action   
124   125   The Dark Knight Rises   Action,Thriller   
284   285                Hercules  Action,Adventure   
344   345            Spider-Man 3  Action,Adventure   
368   369  The Amazing Spider-Man  Action,Adventure   
410   411                   Taken   Action,Thriller   
453   454      Olympus Has Fallen   Action,Thriller   
580   581    Kickboxer: Vengeance            Action   
624   625                 Taken 3   Action,Thriller   
777   778              Final Girl   Action,Thriller   
844   845             Unstoppable   Action,Thriller   
872   873                Red Dawn   Action,Thriller   
923   924               No Escape   Action,Thriller   

                                           Description           Director  \
17   The CIA's most dangerous former operative is d...    Paul Greengrass   
123  In the fourth installment of the fighting fran...    Todor Chapkanov   
124  Eight years after the Joker's reign of anarchy...  Christopher Nolan   
284  Having endured his legendary twelve labors, He...       Brett Ratner   
344  A strange black entity from another world bond...          Sam Raimi   
368  After Peter Parker is bitten by a genetically ...          Marc Webb   
410  A retired CIA agent travels across Europe and ...       Pierre Morel   
453  Disgraced Secret Service agent (and former pre...      Antoine Fuqua   
580         A kick boxer is out to avenge his brother.     John Stockwell   
624  Ex-government operative Bryan Mills is accused...    Olivier Megaton   
777  A man teaches a young woman how to become a co...      Tyler Shields   
844  With an unmanned, half-mile-long freight train...         Tony Scott   
872  A group of teenagers look to save their town f...        Dan Bradley   
923  In their new overseas home, an American family...  John Erick Dowdle   

                                                Actors  Year  \
17   Matt Damon, Tommy Lee Jones, Alicia Vikander,V...  2016   
123  Scott Adkins, Teodora Duhovnikova, Alon Aboutb...  2016   
124  Christian Bale, Tom Hardy, Anne Hathaway,Gary ...  2012   
284  Dwayne Johnson, John Hurt, Ian McShane, Joseph...  2014   
344  Tobey Maguire, Kirsten Dunst, Topher Grace, Th...  2007   
368  Andrew Garfield, Emma Stone, Rhys Ifans, Irrfa...  2012   
410  Liam Neeson, Maggie Grace, Famke Janssen, Lela...  2008   
453  Gerard Butler, Aaron Eckhart, Morgan Freeman,A...  2013   
580  Dave Bautista, Alain Moussi, Gina Carano, Jean...  2016   
624  Liam Neeson, Forest Whitaker, Maggie Grace,Fam...  2014   
777  Abigail Breslin, Wes Bentley, Logan Huffman,Al...  2015   
844  Denzel Washington, Chris Pine, Rosario Dawson,...  2010   
872  Chris Hemsworth, Isabel Lucas, Josh Hutcherson...  2012   
923  Lake Bell, Pierce Brosnan, Owen Wilson,Chatcha...  2015   

     Runtime (Minutes)  Rating    Votes  Revenue (Millions)  Metascore  
17                 123     6.7   150823              162.16       58.0  
123                 86     7.4    10428                 NaN        NaN  
124                164     8.5  1222645              448.13       78.0  
284                 98     6.0   122838               72.66       47.0  
344                139     6.2   406219              336.53       59.0  
368                136     7.0   474320              262.03       66.0  
410                 93     7.8   502961              145.00       50.0  
453                119     6.5   214994               98.90       41.0  
580                 90     4.9     6809              131.56       37.0  
624                109     6.0   144715               89.25       26.0  
777                 90     4.7     9026                 NaN       56.0  
844                 98     6.8   157499               81.56       69.0  
872                 93     5.4    64584               44.80       31.0  
923                103     6.8    57921 

Calculate the average number of words in description and actors

In [263]:
df.Description.str.split().map(len).mean()
df.Actors.str.split().map(len).mean()

7.86

In [266]:
df[['Description','Actors']].applymap(lambda x: len(x.split())).mean()

Description    27.921
Actors          7.860
dtype: float64