In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r'C:\Users\mcoge\Downloads\telecom_churn.csv')

In [3]:
df.head()

State  Account length  Area code International plan Voice mail plan  \
0    KS             128        415                 No             Yes   
1    OH             107        415                 No             Yes   
2    NJ             137        415                 No              No   
3    OH              84        408                Yes              No   
4    OK              75        415                Yes              No   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   Total night minutes  Total night calls  Total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   Total intl minutes  Total intl calls  Total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   Customer service calls  Churn  
0                       1  False  
1                       1  False  
2                       0  False  
3                       2  False  
4                       3  False

In [4]:
df.Churn.value_counts(normalize=True).round(2)

False    0.86
True     0.14
Name: Churn, dtype: float64

In [5]:
df.State.nunique()

51

In [6]:
df.drop('State', axis=1, inplace=True)

In [7]:
dct={'Yes':1, 'No':0}

In [8]:
df['International plan']=df['International plan'].map(dct)
df['Voice mail plan']=df['Voice mail plan'].map(dct)

In [9]:
df.head()

Account length  Area code  International plan  Voice mail plan  \
0             128        415                   0                1   
1             107        415                   0                1   
2             137        415                   0                0   
3              84        408                   1                0   
4              75        415                   1                0   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   Total night minutes  Total night calls  Total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   Total intl minutes  Total intl calls  Total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   Customer service calls  Churn  
0                       1  False  
1                       1  False  
2                       0  False  
3                       2  False  
4                       3  False

In [10]:
df.isna().sum().sum()

0

# Modelling part

In [11]:
!pip install lightgbm

In [12]:
!pip install xgboost

In [13]:
!pip install catboost

In [14]:
# Import function to split the DataFrame
from sklearn.model_selection import train_test_split

# Import different models
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

# Import the scoring
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [ ]:
# Split the DataFrame
X_train, X_test, y_train, y_test = train_test_split (df.drop('Churn', axis=1),
                                                     df.Churn,
                                                    test_size = 1/3,
                                                    random_state = 200
                                                    stratify = df.Churn)

In [16]:
df.Churn.value_counts(normalize = True)

False    0.855086
True     0.144914
Name: Churn, dtype: float64

In [17]:
y_train.value_counts(normalize=True)

False    0.860036
True     0.139964
Name: Churn, dtype: float64

In [18]:
y_test.value_counts(normalize=True)

False    0.845185
True     0.154815
Name: Churn, dtype: float64

# Models

## Calculations of the different scores
`TP` = `True Positive`
`TN` = `True Negative`
`FP` = `False Positive`
`FN` = `False Negative`


#### Accuracy 
`TP` + `TN` / `Total`
#### Precision
`TP` / (`TP` + `FP`)
#### Recall
`TP` / (`TP` + `FN`)
#### F1 Score
(2 * `Precision Score` * `Recall Score`) / (`Precision Score` + `Recall Score`)

### Logistic Regression

In [19]:
model1 = LogisticRegression(max_iter = 1e5)
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_test)
display(confusion_matrix(y_test, y_pred1))
print(accuracy_score(y_test, y_pred1))
print(precision_score(y_test, y_pred1))
print(recall_score(y_test, y_pred1))
print(f1_score(y_test, y_pred1))

array([[908,  31],
       [134,  38]], dtype=int64)

0.8514851485148515
0.5507246376811594
0.22093023255813954
0.31535269709543573


In [20]:
# Precision
38/(38+31)

0.5507246376811594

In [21]:
# Recall
38/(38+134)

0.22093023255813954

In [22]:
# F1 score
2 * ((38/(38+31)) * (38/(38+134)))/ ((38/(38+31)) + (38/(38+134)))

0.31535269709543573

In [23]:
model1 = LogisticRegression(max_iter = 1e5, class_weight='balanced')
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_test)
display(confusion_matrix(y_test, y_pred1))
print(accuracy_score(y_test, y_pred1))
print(precision_score(y_test, y_pred1))
print(recall_score(y_test, y_pred1))
print(f1_score(y_test, y_pred1))

array([[723, 216],
       [ 47, 125]], dtype=int64)

0.7632763276327633
0.36656891495601174
0.7267441860465116
0.4873294346978557


### KNN

In [24]:
model2= KNeighborsClassifier(5)
model2.fit(X_train, y_train)
y_pred2= model2.predict(X_test)
display(confusion_matrix(y_test, y_pred2))
print(accuracy_score(y_test, y_pred2))
print(precision_score(y_test, y_pred2))
print(recall_score(y_test, y_pred2))
print(f1_score(y_test, y_pred2))

array([[913,  26],
       [122,  50]], dtype=int64)

0.8667866786678667
0.6578947368421053
0.29069767441860467
0.40322580645161293


In [25]:
model2= KNeighborsClassifier(5, weights='distance')
model2.fit(X_train, y_train)
y_pred2= model2.predict(X_test)
display(confusion_matrix(y_test, y_pred2))
print(accuracy_score(y_test, y_pred2))
print(precision_score(y_test, y_pred2))
print(recall_score(y_test, y_pred2))
print(f1_score(y_test, y_pred2))

array([[913,  26],
       [121,  51]], dtype=int64)

0.8676867686768677
0.6623376623376623
0.29651162790697677
0.4096385542168675


### SVC

In [26]:
model3= SVC()
model3.fit(X_train, y_train)
y_pred3= model3.predict(X_test)
display(confusion_matrix(y_test, y_pred3))
print(accuracy_score(y_test, y_pred3))
print(precision_score(y_test, y_pred3))
print(recall_score(y_test, y_pred3))
print(f1_score(y_test, y_pred3))

array([[939,   0],
       [172,   0]], dtype=int64)

0.8451845184518452
0.0
0.0
0.0


C:\Users\mcoge\AppData\Roaming\Python\Python38\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Takes too much time, will run it later

### Gaussian NB

In [ ]:
model4= GaussianNB()
model4.fit(X_train, y_train)
y_pred4= model4.predict(X_test)
display(confusion_matrix(y_test, y_pred4))
print(accuracy_score(y_test, y_pred4))
print(precision_score(y_test, y_pred4))
print(recall_score(y_test, y_pred4))
print(f1_score(y_test, y_pred4))

### Decision Tree

In [ ]:
model5= DecisionTreeClassifier()
model5.fit(X_train, y_train)
y_pred5= model5.predict(X_test)
display(confusion_matrix(y_test, y_pred5))
print(accuracy_score(y_test, y_pred5))
print(precision_score(y_test, y_pred5))
print(recall_score(y_test, y_pred5))
print(f1_score(y_test, y_pred5))

### Random Forest

In [ ]:
model6=RandomForestClassifier()
model6.fit(X_train, y_train)
y_pred6 = model6.predict(X_test)
display(confusion_matrix(y_test, y_pred6))
print(accuracy_score(y_test, y_pred6))
print(precision_score(y_test, y_pred6))
print(recall_score(y_test, y_pred6))
print(f1_score(y_test, y_pred6))

In [ ]:
model6=RandomForestClassifier(class_weight='balanced')
model6.fit(X_train, y_train)
y_pred6 = model6.predict(X_test)
display(confusion_matrix(y_test, y_pred6))
print(accuracy_score(y_test, y_pred6))
print(precision_score(y_test, y_pred6))
print(recall_score(y_test, y_pred6))
print(f1_score(y_test, y_pred6))

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
pd.Series(model6.feature_importances_, index=X_train.columns).sort_values().plot.barh()

### AdaBoost

In [ ]:
model7=AdaBoostClassifier()
model7.fit(X_train, y_train)
y_pred7 = model7.predict(X_test)
display(confusion_matrix(y_test, y_pred7))
print(accuracy_score(y_test, y_pred7))
print(precision_score(y_test, y_pred7))
print(recall_score(y_test, y_pred7))
print(f1_score(y_test, y_pred7))

### XGBoost

In [ ]:
model8=XGBClassifier()
model8.fit(X_train, y_train)
y_pred8 = model8.predict(X_test)
display(confusion_matrix(y_test, y_pred8))
print(accuracy_score(y_test, y_pred8))
print(precision_score(y_test, y_pred8))
print(recall_score(y_test, y_pred8))
print(f1_score(y_test, y_pred8))

### LightGBM

In [ ]:
model9=LGBMClassifier()
model9.fit(X_train, y_train)
y_pred9 = model9.predict(X_test)
display(confusion_matrix(y_test, y_pred9))
print(accuracy_score(y_test, y_pred9))
print(precision_score(y_test, y_pred9))
print(recall_score(y_test, y_pred9))
print(f1_score(y_test, y_pred9))

### CatBoost

In [ ]:
model10=CatBoostClassifier()
model10.fit(X_train, y_train.map(int))
y_pred10 = model10.predict(X_test)
display(confusion_matrix(y_test, y_pred10))
print(accuracy_score(y_test, y_pred10))
print(precision_score(y_test, y_pred10))
print(recall_score(y_test, y_pred10))
print(f1_score(y_test, y_pred10))

In [ ]:
y_train.map(int)

### Summary

In [ ]:
a, p, r, f = [], [], [], []
for model in [model1, model2, model3, model4, model5, model6, model7, model8, model9, model10]:
    a.append(accuracy_score(y_test, model.predict(X_test)))
    p.append(precision_score(y_test, model.predict(X_test)))
    r.append(recall_score(y_test, model.predict(X_test)))
    f.append(f1_score(y_test, model.predict(X_test)))

In [ ]:
model_score = pd.DataFrame([a,p,r,f],
             columns = ['LR',
                        'KNN',
                        'SVC',
                        'NB',
                        'DT',
                        'RF',
                        'Ada',
                        'XGB',
                        'LGBM',
                        'Cat']).T.sort_values(by=3, ascending=False).rename(columns={0:'Accuracy', 1: 'Precision', 2: 'Recall', 3: 'F1'}) 

In [ ]:
pd.Series(model9.feature_importances_, index=X_train.columns).sort_values().plot.barh()

In [ ]:
pd.Series(model6.feature_importances_, index=X_train.columns).sort_values().plot.barh()

In [ ]:
import seaborn as sns

In [ ]:
# Create a heatmap of the summary
plt.figure(figsize= (10,10))
sns.heatmap(model_score, annot=True, cmap = 'coolwarm')
plt.show()

In [ ]:
X_test # I dont know who is going to churn, but I want to know

X_test['prediction']=model10.predict(X_test)

In [ ]:
X_test.sample(10)

In [ ]:
model10.predict_proba(X_test)[:,1]