# Cross validation 

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import KFold, StratifiedKFold, RepeatedKFold, RepeatedStratifiedKFold

In [3]:
X,y = make_classification(n_samples=1000, n_features=2, n_redundant=0, random_state=11)

In [4]:
X=(X*100).round()

In [5]:
X

array([[-126., -278.],
       [ -45., -237.],
       [  -5.,  -68.],
       ...,
       [   8., -156.],
       [-192.,  -71.],
       [-130., -105.]])

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
from sklearn.metrics import accuracy_score

In [8]:
kfold=KFold(5, shuffle=True, random_state=11)

In [23]:
list_of_models=[]
list_of_accuracies=[]

In [24]:
for train, test in kfold.split(X):
    print(len(train))
    print(len(test))
    model=KNeighborsClassifier()
    model.fit(X[train],y[train])
    list_of_models.append(model)
    list_of_accuracies.append(accuracy_score(y[test], model.predict(X[test])))
    
    
#this only makes the index, not the proper dataset

800
200
800
200
800
200
800
200
800
200


In [25]:
list_of_accuracies

[0.935, 0.95, 0.965, 0.95, 0.94]

In [28]:
list_of_models

[KNeighborsClassifier(),
 KNeighborsClassifier(),
 KNeighborsClassifier(),
 KNeighborsClassifier(),
 KNeighborsClassifier()]

In [33]:
list(map(lambda x: x.predict(X[-1].reshape(1, -1))[0], list_of_models))

[0, 0, 0, 0, 0]

In [26]:
sum(list_of_accuracies)/5

0.9480000000000001

In [12]:
X.shape

(1000, 2)

In [14]:
train

array([  0,   2,   3,   4,   5,   6,   7,   8,   9,  11,  12,  13,  14,
        16,  20,  21,  22,  24,  25,  26,  28,  29,  30,  31,  33,  34,
        36,  39,  41,  44,  45,  46,  47,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  65,  66,  67,  68,
        69,  70,  71,  73,  74,  77,  78,  82,  83,  85,  86,  87,  88,
        92,  93,  94,  95,  96,  97,  98,  99, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 111, 112, 113, 115, 116, 117, 118, 120, 121,
       122, 123, 124, 126, 127, 128, 129, 130, 134, 135, 136, 137, 139,
       143, 144, 146, 147, 148, 149, 150, 151, 153, 154, 155, 157, 158,
       159, 161, 162, 163, 164, 165, 166, 168, 169, 170, 171, 173, 174,
       175, 176, 177, 179, 180, 181, 182, 183, 184, 186, 187, 188, 189,
       190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
       203, 204, 205, 206, 207, 209, 210, 211, 212, 213, 214, 216, 217,
       218, 219, 220, 221, 222, 223, 226, 228, 229, 230, 232, 23

In [21]:
X[np.random.choice(range(X.shape[0]), size=200)]
#the index

array([[ -82.,  -45.],
       [ -59., -114.],
       [ -22.,  -64.],
       [ 102., -106.],
       [ 230.,   19.],
       [ 126.,  -82.],
       [-106.,  235.],
       [-186.,   88.],
       [  49., -148.],
       [-108.,   58.],
       [ 100.,  116.],
       [ 206.,    0.],
       [-148.,  -84.],
       [ 163.,  -44.],
       [ -72.,   10.],
       [-120.,  -86.],
       [ 193.,   56.],
       [ -72.,   51.],
       [ -71.,  -86.],
       [  77.,  256.],
       [-124.,  211.],
       [   6.,  272.],
       [ 119.,  -81.],
       [ 141.,  112.],
       [-114.,   67.],
       [  58.,   69.],
       [-128., -117.],
       [  46., -148.],
       [ -72.,  148.],
       [  -6., -119.],
       [  98.,  -93.],
       [ 185.,   79.],
       [ 159.,  -49.],
       [ -92.,  -57.],
       [ -69., -147.],
       [-165.,   75.],
       [  29., -155.],
       [  77.,   90.],
       [  57., -143.],
       [  56.,  125.],
       [  94.,  -97.],
       [ -59.,  -17.],
       [  -3., -106.],
       [-11

In [22]:
test

array([  1,  10,  15,  17,  18,  19,  23,  27,  32,  35,  37,  38,  40,
        42,  43,  48,  64,  72,  75,  76,  79,  80,  81,  84,  89,  90,
        91, 100, 110, 114, 119, 125, 131, 132, 133, 138, 140, 141, 142,
       145, 152, 156, 160, 167, 172, 178, 185, 208, 215, 224, 225, 227,
       231, 236, 241, 242, 245, 248, 252, 261, 263, 264, 269, 273, 275,
       283, 303, 314, 321, 326, 328, 332, 335, 337, 338, 343, 362, 363,
       367, 370, 380, 383, 385, 403, 408, 416, 418, 428, 435, 439, 441,
       443, 446, 450, 452, 459, 460, 465, 468, 493, 496, 498, 501, 504,
       505, 506, 509, 511, 518, 529, 546, 555, 577, 579, 580, 583, 585,
       603, 604, 605, 608, 619, 621, 623, 630, 637, 644, 653, 657, 659,
       660, 661, 672, 673, 680, 683, 688, 690, 693, 699, 703, 704, 725,
       727, 734, 735, 748, 753, 756, 764, 765, 766, 787, 792, 799, 805,
       808, 812, 813, 818, 838, 839, 840, 842, 846, 850, 851, 868, 871,
       873, 876, 880, 882, 884, 885, 886, 889, 892, 897, 900, 90

# Hyperparameter tuning

In [34]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [61]:
?KNeighborsClassifier

In [55]:
params={
    'n_neighbors':range(3,12,2),
    'weights': ['uniform', 'distance'],
    'p':range(1,5),
    'n_jobs':[-1],}

In [56]:
params

{'n_neighbors': range(3, 12, 2),
 'weights': ['uniform', 'distance'],
 'p': range(1, 5),
 'n_jobs': [-1]}

In [57]:
model=KNeighborsClassifier()  #-1 = using all the processing power of your computer (one single core)
grid=GridSearchCV(estimator=model, param_grid=params, n_jobs=-1, scoring='recall', verbose =1 )

In [58]:
grid.fit(X,y)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    2.1s
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:    2.4s finished


GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_jobs': [-1], 'n_neighbors': range(3, 12, 2),
                         'p': range(1, 5), 'weights': ['uniform', 'distance']},
             scoring='recall', verbose=1)

In [59]:
grid.best_params_
#these are the best parameters to get the highest recall
#p=1 == manhattan distance

{'n_jobs': -1, 'n_neighbors': 5, 'p': 1, 'weights': 'uniform'}

In [60]:
grid.best_score_

0.9778383838383838

# NOW WITH LINEAR

In [62]:
from sklearn.datasets import load_boston

In [63]:
X,y = load_boston(return_X_y=True)

In [64]:
X.shape

(506, 13)

In [65]:
from sklearn.linear_model import Ridge

In [66]:
Ridge

sklearn.linear_model._ridge.Ridge

In [67]:
from scipy.stats import uniform

In [68]:
#uniform means any number within uniform distribution
params={'alpha': uniform(),      
    'normalize': [False, True],
    'tol':[0.001,0.00001]}

In [69]:
from scipy.stats import norm 

In [76]:
model = Ridge()
rsearch=RandomizedSearchCV(estimator=model, param_distributions=params, n_jobs=-1, verbose= -1, n_iter=100, scoring='neg_mean_absolute_error')

In [77]:
rsearch.fit(X,y)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done 176 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:    0.3s finished


RandomizedSearchCV(estimator=Ridge(), n_iter=100, n_jobs=-1,
                   param_distributions={'alpha': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fdec05e2ca0>,
                                        'normalize': [False, True],
                                        'tol': [0.001, 1e-05]},
                   scoring='neg_mean_absolute_error', verbose=-1)

In [72]:
rsearch.best_params_

{'alpha': 0.33463426835959265, 'normalize': True, 'tol': 0.001}

In [78]:
rsearch.best_score_

#this is default one (R²)

-3.843857406869519

In [75]:
from sklearn.metrics import SCORERS
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

# HYPERPARAMETER + CROSS VALIDATION

In [93]:
from sklearn.datasets import load_wine

In [94]:
X,y = load_wine(return_X_y=True)

In [89]:
X.shape

(442, 10)

In [98]:
from sklearn.metrics import recall_score

In [101]:
recall_score(y, model.predict(X), average='macro')

0.784372430439511

In [108]:
accuracy_score(y, model.predict(X)) 

0.7865168539325843

In [ ]:
#WE can make this better

In [95]:
params={
    'n_neighbors':range(3,12,2),
    'weights': ['uniform', 'distance'],
    'p':range(1,5),
    'n_jobs':[-1],}

In [107]:
model=KNeighborsClassifier()
model.fit(X,y)

KNeighborsClassifier()

In [102]:
model=KNeighborsClassifier()
cv=RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=42)
grid=GridSearchCV(estimator=model, param_grid=params, n_jobs=-1, scoring='recall_macro', verbose=1, cv=cv)

In [103]:
grid.fit(X,y)

Fitting 30 folds for each of 40 candidates, totalling 1200 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    1.7s
[Parallel(n_jobs=-1)]: Done 1152 tasks      | elapsed:    3.1s
[Parallel(n_jobs=-1)]: Done 1200 out of 1200 | elapsed:    3.1s finished


GridSearchCV(cv=RepeatedStratifiedKFold(n_repeats=3, n_splits=10, random_state=42),
             estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_jobs': [-1], 'n_neighbors': range(3, 12, 2),
                         'p': range(1, 5), 'weights': ['uniform', 'distance']},
             scoring='recall_macro', verbose=1)

In [104]:
grid.best_params_

{'n_jobs': -1, 'n_neighbors': 3, 'p': 1, 'weights': 'distance'}

In [105]:
grid.best_score_
#slightly better yes?

0.8046957671957672

In [106]:
grid.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

# Final workflow
1. split into train / test . Dont touch test data until step 6
2. do all the preprocessing of train data (cleaning, transformations, scaling, feature engineering, outlier detection, dropping
3. Split the train data into Train and Validation. Crossvalidation counts.
4. Train the model using Train dataset. Tune Hyperparameters if needed. 
5. Calculate metric chosen on validation dataset. If you are not satisfied with performance go to step 4
6. Test your pipeline (steps 2-4) on your test dataset. If metrics on test dataset are not satisfactory, try once again (fix the pipeline). 
7. If the quality on test dataset is not that different from the one of validation -> pipeline is good. Else - désoél